services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SaltId\ElasticSearchBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

# add more services, or override services that need manual wiring
#    SaltId\ElasticSearchBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"

    SaltId\ElasticSearchBundle\Installer:
        public: true
        arguments:
            # fetch the bundle via expression language
            $bundle: "@=service('kernel').getBundle('ElasticSearchBundle')"

    SaltId\ElasticSearchBundle\Services\ElasticSearch: ~

    SaltId\ElasticSearchBundle\EventListener\DataObjectEventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onDataObjectPreAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd, method: onDataObjectPostAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onDataObjectPreUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onDataObjectPostUpdate }